[package]
name = "seeed-hal-adapter-serialport"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
hardware-loopback = []

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
percent-encoding = { workspace = true }
seeed-hal-core = { path = "../../crates/seeed-hal-core" }
seeed-hal-serial = { path = "../../crates/seeed-hal-serial" }
serial2 = { workspace = true, features = ["unix"] }
serialport = { workspace = true }
tokio = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Devices_Communication",
    "Win32_Foundation",
] }

[dev-dependencies]
seeed-hal-testkit = { path = "../../crates/seeed-hal-testkit" }
