[package]
name = "seeed-hal-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
seeed-hal-core = { path = "../seeed-hal-core", version = "=0.5.0-rc.1"}
seeed-hal-can = { path = "../seeed-hal-can", version = "=0.5.0-rc.1"}
seeed-hal-camera = { path = "../seeed-hal-camera", version = "=0.5.0-rc.1"}
seeed-hal-serial = { path = "../seeed-hal-serial", version = "=0.5.0-rc.1"}
seeed-hal-usb = { path = "../seeed-hal-usb", version = "=0.5.0-rc.1"}
seeed-hal-gpio = { path = "../seeed-hal-gpio", version = "=0.5.0-rc.1"}
tokio = { workspace = true }
