[package]
name = "seeed-hal-testkit"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
seeed-hal-core = { path = "../seeed-hal-core" }
seeed-hal-can = { path = "../seeed-hal-can" }
seeed-hal-camera = { path = "../seeed-hal-camera" }
seeed-hal-serial = { path = "../seeed-hal-serial" }
seeed-hal-usb = { path = "../seeed-hal-usb" }
seeed-hal-gpio = { path = "../seeed-hal-gpio" }
tokio = { workspace = true }
