[package]
name = "robot-hal-windows-security"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[target.'cfg(windows)'.dependencies]
tokio = { workspace = true }
windows-permissions = { workspace = true }
windows-sys = { workspace = true, features = ["Win32_Security"] }

[target.'cfg(windows)'.dev-dependencies]
uuid = { workspace = true }
