[package]
name = "robot-hal-adapter-mediafoundation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
hardware-tests = []

[dependencies]
async-trait = { workspace = true }
robot-hal-camera = { path = "../../crates/robot-hal-camera", version = "=0.5.0-rc.1"}
robot-hal-core = { path = "../../crates/robot-hal-core", version = "=0.5.0-rc.1"}
tokio = { workspace = true }

[target.'cfg(windows)'.dependencies]
bytes = { workspace = true }
windows = { version = "=0.58.0", features = [
    "implement",
    "Win32_Foundation",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
    "Win32_System_Threading",
] }
windows-core = "=0.58.0"
