[package]
name = "seeed-hal-adapter-socketcan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
percent-encoding = { workspace = true }
seeed-hal-can = { path = "../../crates/seeed-hal-can", version = "=0.5.0-rc.1"}
seeed-hal-core = { path = "../../crates/seeed-hal-core", version = "=0.5.0-rc.1"}
tokio = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
can-hal-rs = { workspace = true }
can-hal-socketcan = { workspace = true }
libc = { workspace = true }
neli = "=0.6.5"
socketcan = { version = "=3.5.0", default-features = false, features = ["netlink", "enumerate"] }

[dev-dependencies]
seeed-hal-testkit = { path = "../../crates/seeed-hal-testkit", version = "=0.5.0-rc.1"}
