[package]
name = "seeed-hal-protocol"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
bytes = { workspace = true }
prost = { workspace = true }
seeed-hal-can = { path = "../seeed-hal-can" }
seeed-hal-core = { path = "../seeed-hal-core" }
seeed-hal-runtime = { path = "../seeed-hal-runtime" }
seeed-hal-serial = { path = "../seeed-hal-serial" }
seeed-hal-usb = { path = "../seeed-hal-usb" }
seeed-hal-gpio = { path = "../seeed-hal-gpio" }

[build-dependencies]
prost-build = { workspace = true }
protoc-bin-vendored = { workspace = true }
