"""Public, protobuf-independent Robot HAL Python API."""

from importlib.metadata import version as _distribution_version

__version__ = _distribution_version("robot-hal")

from .client import (
    EventSubscription,
    HalClient,
    IdentityQuality,
    LeaseMode,
    ResourceDescriptor,
    ResourceSelector,
    RuntimeEvent,
    TransportKind,
)
from .can import (
    CanBatchSendError,
    CanBitTiming,
    CanBusState,
    CanBusStatus,
    CanClassicDataFrame,
    CanClassicRemoteFrame,
    CanConfigureConfig,
    CanErrorClass,
    CanErrorFrame,
    CanFdDataFrame,
    CanFilter,
    CanFilterSet,
    CanFrame,
    CanFrameClasses,
    CanId,
    CanIdFormat,
    CanLinkExpectation,
    CanMode,
    CanOpenConfig,
    CanSession,
    CanTimestamp,
    CanTimestampSource,
    ClassicDataFrame,
    ClassicRemoteFrame,
    ErrorFrame,
    FdDataFrame,
    ReceivedCanFrame,
)
from .errors import ErrorCategory, HalError
from .serial import (
    ControlLines,
    DataBits,
    FlowControl,
    Parity,
    SerialConfig,
    SerialSession,
    StopBits,
)
from .usb import UsbSession, UsbTransfer, UsbTransferKind
from .gpio import (
    GpioBias,
    GpioDirection,
    GpioDrive,
    GpioEdge,
    GpioEdgeEvent,
    GpioEdgeRequest,
    GpioLineConfig,
    GpioSession,
)
from .camera import (
    CameraControlDescriptor,
    CameraFormat,
    CameraSession,
    ControlEnumValues,
    ControlKind,
    ControlRange,
    ControlValue,
    FrameLease,
    MappingDescriptor,
    PixelFormat,
)

__all__ = [
    "__version__",
    "ControlLines",
    "CanBatchSendError",
    "CanBitTiming",
    "CanBusState",
    "CanBusStatus",
    "CanClassicDataFrame",
    "CanClassicRemoteFrame",
    "CanConfigureConfig",
    "CanErrorClass",
    "CanErrorFrame",
    "CanFdDataFrame",
    "CanFilter",
    "CanFilterSet",
    "CanFrame",
    "CanFrameClasses",
    "CanId",
    "CanIdFormat",
    "CanLinkExpectation",
    "CanMode",
    "CanOpenConfig",
    "CanSession",
    "CameraControlDescriptor",
    "CameraFormat",
    "CameraSession",
    "ControlEnumValues",
    "ControlKind",
    "ControlRange",
    "ControlValue",
    "FrameLease",
    "MappingDescriptor",
    "PixelFormat",
    "CanTimestamp",
    "CanTimestampSource",
    "ClassicDataFrame",
    "ClassicRemoteFrame",
    "DataBits",
    "ErrorCategory",
    "EventSubscription",
    "FlowControl",
    "GpioBias",
    "GpioDirection",
    "GpioDrive",
    "GpioEdge",
    "GpioEdgeEvent",
    "GpioEdgeRequest",
    "GpioLineConfig",
    "GpioSession",
    "HalClient",
    "HalError",
    "IdentityQuality",
    "LeaseMode",
    "ErrorFrame",
    "FdDataFrame",
    "Parity",
    "ResourceDescriptor",
    "ResourceSelector",
    "RuntimeEvent",
    "ReceivedCanFrame",
    "SerialConfig",
    "SerialSession",
    "StopBits",
    "TransportKind",
    "UsbSession",
    "UsbTransfer",
    "UsbTransferKind",
]
