[package]
name = "robot-hal-adapter-v4l2"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
hardware-tests = []

[dependencies]
async-trait = { workspace = true }
robot-hal-camera = { path = "../../crates/robot-hal-camera", version = "=0.5.0-rc.1"}
robot-hal-core = { path = "../../crates/robot-hal-core", version = "=0.5.0-rc.1"}
tokio = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
bytes = { workspace = true }
v4l = "=0.14.0"
