[package]
name = "robot-hal-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
test-support = []

[dependencies]
bytes = { workspace = true }
robot-hal-core = { path = "../robot-hal-core", version = "=0.5.0-rc.1"}
robot-hal-can = { path = "../robot-hal-can", version = "=0.5.0-rc.1"}
robot-hal-serial = { path = "../robot-hal-serial", version = "=0.5.0-rc.1"}
robot-hal-usb = { path = "../robot-hal-usb", version = "=0.5.0-rc.1"}
robot-hal-gpio = { path = "../robot-hal-gpio", version = "=0.5.0-rc.1"}
robot-hal-camera = { path = "../robot-hal-camera", version = "=0.5.0-rc.1"}
robot-hal-adapter-shared-memory = { path = "../../adapters/shared-memory", version = "=0.5.0-rc.1"}
tokio = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
robot-hal-testkit = { path = "../robot-hal-testkit", version = "=0.5.0-rc.1"}
tokio = { workspace = true, features = ["test-util"] }

[[test]]
name = "gpio_runtime"
required-features = ["test-support"]

[[test]]
name = "usb_runtime"
required-features = ["test-support"]
