[package]
name = "robot-hal-adapter-avfoundation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
hardware-tests = []

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
robot-hal-camera = { path = "../../crates/robot-hal-camera", version = "=0.5.0-rc.1"}
robot-hal-core = { path = "../../crates/robot-hal-core", version = "=0.5.0-rc.1"}
tokio = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
dispatch2 = "0.3"
objc2-av-foundation = { version = "=0.3.1", features = [
    "AVCaptureDevice",
    "AVCaptureInput",
    "AVCaptureOutputBase",
    "AVCaptureSession",
    "AVCaptureSessionPreset",
    "AVCaptureVideoDataOutput",
    "AVError",
    "AVMediaFormat",
    "block2",
    "objc2-core-media",
] }
block2 = "0.6"
objc2-foundation = { version = "=0.3.1", features = ["NSDictionary", "NSError", "NSNotification", "NSOperation", "block2"] }
objc2-core-foundation = "=0.3.2"
objc2-core-media = { version = "=0.3.1", features = ["CMBlockBuffer", "CMFormatDescription", "CMSampleBuffer", "CMTime", "objc2-core-video"] }
objc2-core-video = { version = "=0.3.1", features = ["CVBase", "CVBuffer", "CVImageBuffer", "CVPixelBuffer", "CVReturn"] }
